// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buddies.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBuddyExists = `-- name: CheckBuddyExists :one
SELECT EXISTS(
    SELECT 1 FROM aecheck.buddies WHERE buddy_id = $1
) as exists
`

func (q *Queries) CheckBuddyExists(ctx context.Context, buddyID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkBuddyExists, buddyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBuddyWithDetails = `-- name: GetBuddyWithDetails :one
SELECT
    t.en as english_name,
    c.style,
    c.aewiki_url as partner_aewiki_url,
    b.aewiki_url,
    b.seesaa_url
FROM aecheck.buddies b
LEFT JOIN aecheck.characters c ON b.character_id = c.character_id
LEFT JOIN aecheck.translations t ON c.character_code = t.key
WHERE b.buddy_id = $1
`

type GetBuddyWithDetailsRow struct {
	EnglishName      pgtype.Text `json:"english_name"`
	Style            pgtype.Text `json:"style"`
	PartnerAewikiUrl pgtype.Text `json:"partner_aewiki_url"`
	AewikiUrl        pgtype.Text `json:"aewiki_url"`
	SeesaaUrl        pgtype.Text `json:"seesaa_url"`
}

func (q *Queries) GetBuddyWithDetails(ctx context.Context, buddyID string) (GetBuddyWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getBuddyWithDetails, buddyID)
	var i GetBuddyWithDetailsRow
	err := row.Scan(
		&i.EnglishName,
		&i.Style,
		&i.PartnerAewikiUrl,
		&i.AewikiUrl,
		&i.SeesaaUrl,
	)
	return i, err
}

const getCharacterIDByWikiURL = `-- name: GetCharacterIDByWikiURL :one
SELECT character_id
FROM aecheck.characters
WHERE aewiki_url = $1
LIMIT 1
`

func (q *Queries) GetCharacterIDByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getCharacterIDByWikiURL, aewikiUrl)
	var character_id string
	err := row.Scan(&character_id)
	return character_id, err
}

const insertBuddyWithCharacter = `-- name: InsertBuddyWithCharacter :exec
INSERT INTO aecheck.buddies (buddy_id, character_id, aewiki_url, seesaa_url, created_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
`

type InsertBuddyWithCharacterParams struct {
	BuddyID     string      `json:"buddy_id"`
	CharacterID pgtype.Text `json:"character_id"`
	AewikiUrl   pgtype.Text `json:"aewiki_url"`
	SeesaaUrl   pgtype.Text `json:"seesaa_url"`
}

func (q *Queries) InsertBuddyWithCharacter(ctx context.Context, arg InsertBuddyWithCharacterParams) error {
	_, err := q.db.Exec(ctx, insertBuddyWithCharacter,
		arg.BuddyID,
		arg.CharacterID,
		arg.AewikiUrl,
		arg.SeesaaUrl,
	)
	return err
}

const insertBuddyWithGetPath = `-- name: InsertBuddyWithGetPath :exec
INSERT INTO aecheck.buddies (buddy_id, get_path, aewiki_url, seesaa_url, created_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
`

type InsertBuddyWithGetPathParams struct {
	BuddyID   string      `json:"buddy_id"`
	GetPath   pgtype.Text `json:"get_path"`
	AewikiUrl pgtype.Text `json:"aewiki_url"`
	SeesaaUrl pgtype.Text `json:"seesaa_url"`
}

func (q *Queries) InsertBuddyWithGetPath(ctx context.Context, arg InsertBuddyWithGetPathParams) error {
	_, err := q.db.Exec(ctx, insertBuddyWithGetPath,
		arg.BuddyID,
		arg.GetPath,
		arg.AewikiUrl,
		arg.SeesaaUrl,
	)
	return err
}

const updateBuddyWithCharacter = `-- name: UpdateBuddyWithCharacter :exec
UPDATE aecheck.buddies
SET
    character_id = $2,
    aewiki_url = $3,
    seesaa_url = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE buddy_id = $1
`

type UpdateBuddyWithCharacterParams struct {
	BuddyID     string      `json:"buddy_id"`
	CharacterID pgtype.Text `json:"character_id"`
	AewikiUrl   pgtype.Text `json:"aewiki_url"`
	SeesaaUrl   pgtype.Text `json:"seesaa_url"`
}

func (q *Queries) UpdateBuddyWithCharacter(ctx context.Context, arg UpdateBuddyWithCharacterParams) error {
	_, err := q.db.Exec(ctx, updateBuddyWithCharacter,
		arg.BuddyID,
		arg.CharacterID,
		arg.AewikiUrl,
		arg.SeesaaUrl,
	)
	return err
}

const updateBuddyWithGetPath = `-- name: UpdateBuddyWithGetPath :exec
UPDATE aecheck.buddies
SET
    get_path = $2,
    aewiki_url = $3,
    seesaa_url = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE buddy_id = $1
`

type UpdateBuddyWithGetPathParams struct {
	BuddyID   string      `json:"buddy_id"`
	GetPath   pgtype.Text `json:"get_path"`
	AewikiUrl pgtype.Text `json:"aewiki_url"`
	SeesaaUrl pgtype.Text `json:"seesaa_url"`
}

func (q *Queries) UpdateBuddyWithGetPath(ctx context.Context, arg UpdateBuddyWithGetPathParams) error {
	_, err := q.db.Exec(ctx, updateBuddyWithGetPath,
		arg.BuddyID,
		arg.GetPath,
		arg.AewikiUrl,
		arg.SeesaaUrl,
	)
	return err
}
