// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkCharacterExists = `-- name: CheckCharacterExists :one
SELECT EXISTS(
    SELECT 1 FROM aecheck.characters WHERE character_id = $1
) as exists
`

func (q *Queries) CheckCharacterExists(ctx context.Context, characterID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkCharacterExists, characterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const copyCharacterToNewID = `-- name: CopyCharacterToNewID :exec
INSERT INTO aecheck.characters (
    character_id,
    character_code,
    category,
    style,
    light_shadow,
    max_manifest,
    is_awaken,
    is_alter,
    alter_character,
    aewiki_url,
    seesaa_url,
    update_date,
    custom_manifest,
    personalities_data,
    dungeons_data,
    buddy_data,
    created_at,
    updated_at
)
SELECT
    $1,
    c.character_code,
    c.category,
    c.style,
    c.light_shadow,
    c.max_manifest,
    c.is_awaken,
    c.is_alter,
    c.alter_character,
    c.aewiki_url,
    c.seesaa_url,
    c.update_date,
    c.custom_manifest,
    c.personalities_data,
    c.dungeons_data,
    c.buddy_data,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM aecheck.characters c
WHERE c.character_id = $2
`

type CopyCharacterToNewIDParams struct {
	CharacterID   string `json:"character_id"`
	CharacterID_2 string `json:"character_id_2"`
}

func (q *Queries) CopyCharacterToNewID(ctx context.Context, arg CopyCharacterToNewIDParams) error {
	_, err := q.db.Exec(ctx, copyCharacterToNewID, arg.CharacterID, arg.CharacterID_2)
	return err
}

const getCharacterCodeByWikiURL = `-- name: GetCharacterCodeByWikiURL :one
SELECT character_code
FROM aecheck.characters
WHERE aewiki_url = $1
LIMIT 1
`

func (q *Queries) GetCharacterCodeByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getCharacterCodeByWikiURL, aewikiUrl)
	var character_code string
	err := row.Scan(&character_code)
	return character_code, err
}

const getCharacterJSONBData = `-- name: GetCharacterJSONBData :one
SELECT
    personalities_data,
    dungeons_data,
    buddy_data
FROM aecheck.characters
WHERE character_id = $1
`

type GetCharacterJSONBDataRow struct {
	PersonalitiesData []byte `json:"personalities_data"`
	DungeonsData      []byte `json:"dungeons_data"`
	BuddyData         []byte `json:"buddy_data"`
}

func (q *Queries) GetCharacterJSONBData(ctx context.Context, characterID string) (GetCharacterJSONBDataRow, error) {
	row := q.db.QueryRow(ctx, getCharacterJSONBData, characterID)
	var i GetCharacterJSONBDataRow
	err := row.Scan(&i.PersonalitiesData, &i.DungeonsData, &i.BuddyData)
	return i, err
}

const getCharacterWithTranslation = `-- name: GetCharacterWithTranslation :one
SELECT
    t.en as english_name,
    c.style,
    c.light_shadow,
    c.category,
    c.max_manifest,
    c.is_awaken,
    c.is_alter,
    c.alter_character,
    c.aewiki_url,
    c.seesaa_url,
    TO_CHAR(c.update_date::timestamp, 'YYYY-MM-DD') as update_date,
    c.custom_manifest
FROM aecheck.characters c
LEFT JOIN aecheck.translations t ON c.character_code = t.key
WHERE c.character_id = $1
`

type GetCharacterWithTranslationRow struct {
	EnglishName    pgtype.Text `json:"english_name"`
	Style          string      `json:"style"`
	LightShadow    string      `json:"light_shadow"`
	Category       string      `json:"category"`
	MaxManifest    int32       `json:"max_manifest"`
	IsAwaken       bool        `json:"is_awaken"`
	IsAlter        bool        `json:"is_alter"`
	AlterCharacter pgtype.Text `json:"alter_character"`
	AewikiUrl      pgtype.Text `json:"aewiki_url"`
	SeesaaUrl      pgtype.Text `json:"seesaa_url"`
	UpdateDate     string      `json:"update_date"`
	CustomManifest pgtype.Bool `json:"custom_manifest"`
}

func (q *Queries) GetCharacterWithTranslation(ctx context.Context, characterID string) (GetCharacterWithTranslationRow, error) {
	row := q.db.QueryRow(ctx, getCharacterWithTranslation, characterID)
	var i GetCharacterWithTranslationRow
	err := row.Scan(
		&i.EnglishName,
		&i.Style,
		&i.LightShadow,
		&i.Category,
		&i.MaxManifest,
		&i.IsAwaken,
		&i.IsAlter,
		&i.AlterCharacter,
		&i.AewikiUrl,
		&i.SeesaaUrl,
		&i.UpdateDate,
		&i.CustomManifest,
	)
	return i, err
}

const getFirstCharacterByCode = `-- name: GetFirstCharacterByCode :one
SELECT
    character_id,
    style,
    updated_at
FROM aecheck.characters
WHERE character_code = $1
ORDER BY character_id ASC
LIMIT 1
`

type GetFirstCharacterByCodeRow struct {
	CharacterID string           `json:"character_id"`
	Style       string           `json:"style"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetFirstCharacterByCode(ctx context.Context, characterCode string) (GetFirstCharacterByCodeRow, error) {
	row := q.db.QueryRow(ctx, getFirstCharacterByCode, characterCode)
	var i GetFirstCharacterByCodeRow
	err := row.Scan(&i.CharacterID, &i.Style, &i.UpdatedAt)
	return i, err
}

const insertCharacter = `-- name: InsertCharacter :exec
INSERT INTO aecheck.characters (
    character_id,
    character_code,
    category,
    style,
    light_shadow,
    max_manifest,
    is_awaken,
    is_alter,
    alter_character,
    aewiki_url,
    seesaa_url,
    update_date,
    custom_manifest,
    personalities_data,
    dungeons_data,
    buddy_data,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
`

type InsertCharacterParams struct {
	CharacterID       string      `json:"character_id"`
	CharacterCode     string      `json:"character_code"`
	Category          string      `json:"category"`
	Style             string      `json:"style"`
	LightShadow       string      `json:"light_shadow"`
	MaxManifest       int32       `json:"max_manifest"`
	IsAwaken          bool        `json:"is_awaken"`
	IsAlter           bool        `json:"is_alter"`
	AlterCharacter    pgtype.Text `json:"alter_character"`
	AewikiUrl         pgtype.Text `json:"aewiki_url"`
	SeesaaUrl         pgtype.Text `json:"seesaa_url"`
	UpdateDate        pgtype.Date `json:"update_date"`
	CustomManifest    pgtype.Bool `json:"custom_manifest"`
	PersonalitiesData []byte      `json:"personalities_data"`
	DungeonsData      []byte      `json:"dungeons_data"`
	BuddyData         []byte      `json:"buddy_data"`
}

func (q *Queries) InsertCharacter(ctx context.Context, arg InsertCharacterParams) error {
	_, err := q.db.Exec(ctx, insertCharacter,
		arg.CharacterID,
		arg.CharacterCode,
		arg.Category,
		arg.Style,
		arg.LightShadow,
		arg.MaxManifest,
		arg.IsAwaken,
		arg.IsAlter,
		arg.AlterCharacter,
		arg.AewikiUrl,
		arg.SeesaaUrl,
		arg.UpdateDate,
		arg.CustomManifest,
		arg.PersonalitiesData,
		arg.DungeonsData,
		arg.BuddyData,
	)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :exec
UPDATE aecheck.characters
SET
    character_code = $2,
    category = $3,
    style = $4,
    light_shadow = $5,
    max_manifest = $6,
    is_awaken = $7,
    is_alter = $8,
    alter_character = $9,
    aewiki_url = $10,
    seesaa_url = $11,
    update_date = $12,
    custom_manifest = $13,
    personalities_data = $14,
    dungeons_data = $15,
    buddy_data = $16,
    updated_at = CURRENT_TIMESTAMP
WHERE character_id = $1
`

type UpdateCharacterParams struct {
	CharacterID       string      `json:"character_id"`
	CharacterCode     string      `json:"character_code"`
	Category          string      `json:"category"`
	Style             string      `json:"style"`
	LightShadow       string      `json:"light_shadow"`
	MaxManifest       int32       `json:"max_manifest"`
	IsAwaken          bool        `json:"is_awaken"`
	IsAlter           bool        `json:"is_alter"`
	AlterCharacter    pgtype.Text `json:"alter_character"`
	AewikiUrl         pgtype.Text `json:"aewiki_url"`
	SeesaaUrl         pgtype.Text `json:"seesaa_url"`
	UpdateDate        pgtype.Date `json:"update_date"`
	CustomManifest    pgtype.Bool `json:"custom_manifest"`
	PersonalitiesData []byte      `json:"personalities_data"`
	DungeonsData      []byte      `json:"dungeons_data"`
	BuddyData         []byte      `json:"buddy_data"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error {
	_, err := q.db.Exec(ctx, updateCharacter,
		arg.CharacterID,
		arg.CharacterCode,
		arg.Category,
		arg.Style,
		arg.LightShadow,
		arg.MaxManifest,
		arg.IsAwaken,
		arg.IsAlter,
		arg.AlterCharacter,
		arg.AewikiUrl,
		arg.SeesaaUrl,
		arg.UpdateDate,
		arg.CustomManifest,
		arg.PersonalitiesData,
		arg.DungeonsData,
		arg.BuddyData,
	)
	return err
}

const updateCharacterToFourStar = `-- name: UpdateCharacterToFourStar :exec
UPDATE aecheck.characters
SET
    style = '☆4',
    max_manifest = 0,
    is_awaken = false,
    is_alter = false,
    custom_manifest = false,
    updated_at = CURRENT_TIMESTAMP
WHERE character_id = $1
`

func (q *Queries) UpdateCharacterToFourStar(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, updateCharacterToFourStar, characterID)
	return err
}
