// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dungeon_mappings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDungeonMappings = `-- name: GetDungeonMappings :many
SELECT
    d.dungeon_id,
    t.en as english_name
FROM aecheck.dungeon_mappings d
LEFT JOIN aecheck.translations t ON d.dungeon_id = t.key
WHERE d.character_id = $1
  AND d.deleted_at IS NULL
`

type GetDungeonMappingsRow struct {
	DungeonID   string      `json:"dungeon_id"`
	EnglishName pgtype.Text `json:"english_name"`
}

func (q *Queries) GetDungeonMappings(ctx context.Context, characterID string) ([]GetDungeonMappingsRow, error) {
	rows, err := q.db.Query(ctx, getDungeonMappings, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDungeonMappingsRow{}
	for rows.Next() {
		var i GetDungeonMappingsRow
		if err := rows.Scan(&i.DungeonID, &i.EnglishName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDungeonMapping = `-- name: InsertDungeonMapping :exec
INSERT INTO aecheck.dungeon_mappings (character_id, dungeon_id, description, created_at)
VALUES ($1, $2, NULL, CURRENT_TIMESTAMP)
`

type InsertDungeonMappingParams struct {
	CharacterID string `json:"character_id"`
	DungeonID   string `json:"dungeon_id"`
}

func (q *Queries) InsertDungeonMapping(ctx context.Context, arg InsertDungeonMappingParams) error {
	_, err := q.db.Exec(ctx, insertDungeonMapping, arg.CharacterID, arg.DungeonID)
	return err
}

const purgeDeletedDungeonMappings = `-- name: PurgeDeletedDungeonMappings :exec
DELETE FROM aecheck.dungeon_mappings
WHERE character_id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) PurgeDeletedDungeonMappings(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, purgeDeletedDungeonMappings, characterID)
	return err
}

const softDeleteDungeonMappings = `-- name: SoftDeleteDungeonMappings :exec
UPDATE aecheck.dungeon_mappings
SET
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE character_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDungeonMappings(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, softDeleteDungeonMappings, characterID)
	return err
}
