// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dungeons.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDungeonByID = `-- name: GetDungeonByID :one
SELECT
    dungeon_id,
    altema_url,
    aewiki_url
FROM aecheck.dungeons
WHERE dungeon_id = $1
`

type GetDungeonByIDRow struct {
	DungeonID string      `json:"dungeon_id"`
	AltemaUrl pgtype.Text `json:"altema_url"`
	AewikiUrl pgtype.Text `json:"aewiki_url"`
}

func (q *Queries) GetDungeonByID(ctx context.Context, dungeonID string) (GetDungeonByIDRow, error) {
	row := q.db.QueryRow(ctx, getDungeonByID, dungeonID)
	var i GetDungeonByIDRow
	err := row.Scan(&i.DungeonID, &i.AltemaUrl, &i.AewikiUrl)
	return i, err
}

const getDungeonsByIDs = `-- name: GetDungeonsByIDs :many
SELECT
    dungeon_id,
    altema_url,
    aewiki_url
FROM aecheck.dungeons
WHERE dungeon_id = ANY($1::text[])
`

type GetDungeonsByIDsRow struct {
	DungeonID string      `json:"dungeon_id"`
	AltemaUrl pgtype.Text `json:"altema_url"`
	AewikiUrl pgtype.Text `json:"aewiki_url"`
}

func (q *Queries) GetDungeonsByIDs(ctx context.Context, dollar_1 []string) ([]GetDungeonsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getDungeonsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDungeonsByIDsRow{}
	for rows.Next() {
		var i GetDungeonsByIDsRow
		if err := rows.Scan(&i.DungeonID, &i.AltemaUrl, &i.AewikiUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
