// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AecheckBuddy struct {
	BuddyID     string           `json:"buddy_id"`
	CharacterID pgtype.Text      `json:"character_id"`
	GetPath     pgtype.Text      `json:"get_path"`
	SeesaaUrl   pgtype.Text      `json:"seesaa_url"`
	AewikiUrl   pgtype.Text      `json:"aewiki_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type AecheckCharacter struct {
	CharacterID       string           `json:"character_id"`
	CharacterCode     string           `json:"character_code"`
	Category          string           `json:"category"`
	Style             string           `json:"style"`
	LightShadow       string           `json:"light_shadow"`
	MaxManifest       int32            `json:"max_manifest"`
	IsAwaken          bool             `json:"is_awaken"`
	IsAlter           bool             `json:"is_alter"`
	AlterCharacter    pgtype.Text      `json:"alter_character"`
	SeesaaUrl         pgtype.Text      `json:"seesaa_url"`
	AewikiUrl         pgtype.Text      `json:"aewiki_url"`
	UpdateDate        pgtype.Date      `json:"update_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
	CustomManifest    pgtype.Bool      `json:"custom_manifest"`
	PersonalitiesData []byte           `json:"personalities_data"`
	DungeonsData      []byte           `json:"dungeons_data"`
	BuddyData         []byte           `json:"buddy_data"`
}

type AecheckDungeon struct {
	DungeonID string           `json:"dungeon_id"`
	AltemaUrl pgtype.Text      `json:"altema_url"`
	AewikiUrl pgtype.Text      `json:"aewiki_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type AecheckTranslation struct {
	Key       string           `json:"key"`
	Ko        string           `json:"ko"`
	En        string           `json:"en"`
	Ja        string           `json:"ja"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
