// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personality_mappings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPersonalityMappings = `-- name: GetPersonalityMappings :many
SELECT
    p.personality_id,
    t.en as english_name
FROM aecheck.personality_mappings p
LEFT JOIN aecheck.translations t ON p.personality_id = t.key
WHERE p.character_id = $1
  AND p.deleted_at IS NULL
`

type GetPersonalityMappingsRow struct {
	PersonalityID string      `json:"personality_id"`
	EnglishName   pgtype.Text `json:"english_name"`
}

func (q *Queries) GetPersonalityMappings(ctx context.Context, characterID string) ([]GetPersonalityMappingsRow, error) {
	rows, err := q.db.Query(ctx, getPersonalityMappings, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPersonalityMappingsRow{}
	for rows.Next() {
		var i GetPersonalityMappingsRow
		if err := rows.Scan(&i.PersonalityID, &i.EnglishName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPersonalityMapping = `-- name: InsertPersonalityMapping :exec
INSERT INTO aecheck.personality_mappings (character_id, personality_id, description, created_at)
VALUES ($1, $2, NULL, CURRENT_TIMESTAMP)
`

type InsertPersonalityMappingParams struct {
	CharacterID   string `json:"character_id"`
	PersonalityID string `json:"personality_id"`
}

func (q *Queries) InsertPersonalityMapping(ctx context.Context, arg InsertPersonalityMappingParams) error {
	_, err := q.db.Exec(ctx, insertPersonalityMapping, arg.CharacterID, arg.PersonalityID)
	return err
}

const purgeDeletedPersonalityMappings = `-- name: PurgeDeletedPersonalityMappings :exec
DELETE FROM aecheck.personality_mappings
WHERE character_id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) PurgeDeletedPersonalityMappings(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, purgeDeletedPersonalityMappings, characterID)
	return err
}

const softDeletePersonalityMappings = `-- name: SoftDeletePersonalityMappings :exec
UPDATE aecheck.personality_mappings
SET
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE character_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePersonalityMappings(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, softDeletePersonalityMappings, characterID)
	return err
}
