// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckBuddyExists(ctx context.Context, buddyID string) (bool, error)
	CheckCharacterExists(ctx context.Context, characterID string) (bool, error)
	CheckFiveStarExistsByCode(ctx context.Context, characterCode string) (bool, error)
	CheckTranslationExists(ctx context.Context, key string) (bool, error)
	ClearAllTiers(ctx context.Context) error
	CopyCharacterToNewID(ctx context.Context, arg CopyCharacterToNewIDParams) error
	GetBuddyCount(ctx context.Context) (int64, error)
	GetBuddyIDByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error)
	GetBuddyWithDetails(ctx context.Context, buddyID string) (GetBuddyWithDetailsRow, error)
	GetCharacterByCodeAndStyle(ctx context.Context, arg GetCharacterByCodeAndStyleParams) (string, error)
	GetCharacterByEnglishName(ctx context.Context, arg GetCharacterByEnglishNameParams) (GetCharacterByEnglishNameRow, error)
	GetCharacterByJapaneseName(ctx context.Context, arg GetCharacterByJapaneseNameParams) (GetCharacterByJapaneseNameRow, error)
	GetCharacterCodeByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error)
	GetCharacterIDByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error)
	GetCharacterJSONBData(ctx context.Context, characterID string) (GetCharacterJSONBDataRow, error)
	GetCharacterTranslationByEnglishName(ctx context.Context, en string) (GetCharacterTranslationByEnglishNameRow, error)
	GetCharacterWithTranslation(ctx context.Context, characterID string) (GetCharacterWithTranslationRow, error)
	GetClassTranslationByEnglishName(ctx context.Context, en string) (GetClassTranslationByEnglishNameRow, error)
	GetDungeonByID(ctx context.Context, dungeonID string) (GetDungeonByIDRow, error)
	GetFirstCharacterByCode(ctx context.Context, characterCode string) (GetFirstCharacterByCodeRow, error)
	GetKeyByEnglishName(ctx context.Context, en string) (string, error)
	GetRandomBuddyWikiURL(ctx context.Context) (pgtype.Text, error)
	GetRandomCharacterWikiURL(ctx context.Context) (pgtype.Text, error)
	GetTranslation(ctx context.Context, key string) (GetTranslationRow, error)
	GetTranslationsByJapaneseList(ctx context.Context, dollar_1 []string) ([]GetTranslationsByJapaneseListRow, error)
	InsertBuddyWithCharacter(ctx context.Context, arg InsertBuddyWithCharacterParams) error
	InsertBuddyWithGetPath(ctx context.Context, arg InsertBuddyWithGetPathParams) error
	InsertCharacter(ctx context.Context, arg InsertCharacterParams) error
	InsertTranslation(ctx context.Context, arg InsertTranslationParams) error
	UpdateBuddyWithCharacter(ctx context.Context, arg UpdateBuddyWithCharacterParams) error
	UpdateBuddyWithGetPath(ctx context.Context, arg UpdateBuddyWithGetPathParams) error
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error
	UpdateCharacterBuddyData(ctx context.Context, arg UpdateCharacterBuddyDataParams) error
	UpdateCharacterTier(ctx context.Context, arg UpdateCharacterTierParams) error
	UpdateCharacterToFourStar(ctx context.Context, characterID string) error
	UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) error
}

var _ Querier = (*Queries)(nil)
