// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckBuddyExists(ctx context.Context, buddyID string) (bool, error)
	CheckCharacterExists(ctx context.Context, characterID string) (bool, error)
	CheckTranslationExists(ctx context.Context, key string) (bool, error)
	CopyCharacterToNewID(ctx context.Context, arg CopyCharacterToNewIDParams) error
	GetBuddyWithDetails(ctx context.Context, buddyID string) (GetBuddyWithDetailsRow, error)
	GetCharacterCodeByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error)
	GetCharacterIDByWikiURL(ctx context.Context, aewikiUrl pgtype.Text) (string, error)
	GetCharacterJSONBData(ctx context.Context, characterID string) (GetCharacterJSONBDataRow, error)
	GetCharacterWithTranslation(ctx context.Context, characterID string) (GetCharacterWithTranslationRow, error)
	GetDungeonByID(ctx context.Context, dungeonID string) (GetDungeonByIDRow, error)
	GetDungeonsByIDs(ctx context.Context, dollar_1 []string) ([]GetDungeonsByIDsRow, error)
	GetFirstCharacterByCode(ctx context.Context, characterCode string) (GetFirstCharacterByCodeRow, error)
	GetKeyByEnglishName(ctx context.Context, en string) (string, error)
	GetPersonalityMappings(ctx context.Context, characterID string) ([]GetPersonalityMappingsRow, error)
	GetTranslation(ctx context.Context, key string) (GetTranslationRow, error)
	InsertBuddyWithCharacter(ctx context.Context, arg InsertBuddyWithCharacterParams) error
	InsertBuddyWithGetPath(ctx context.Context, arg InsertBuddyWithGetPathParams) error
	InsertCharacter(ctx context.Context, arg InsertCharacterParams) error
	InsertPersonalityMapping(ctx context.Context, arg InsertPersonalityMappingParams) error
	InsertTranslation(ctx context.Context, arg InsertTranslationParams) error
	PurgeDeletedPersonalityMappings(ctx context.Context, characterID string) error
	SoftDeletePersonalityMappings(ctx context.Context, characterID string) error
	UpdateBuddyWithCharacter(ctx context.Context, arg UpdateBuddyWithCharacterParams) error
	UpdateBuddyWithGetPath(ctx context.Context, arg UpdateBuddyWithGetPathParams) error
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error
	UpdateCharacterToFourStar(ctx context.Context, characterID string) error
	UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) error
}

var _ Querier = (*Queries)(nil)
