// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package postgres

import (
	"context"
)

const checkTranslationExists = `-- name: CheckTranslationExists :one
SELECT EXISTS(
    SELECT 1 FROM aecheck.translations WHERE key = $1
) as exists
`

func (q *Queries) CheckTranslationExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, checkTranslationExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getKeyByEnglishName = `-- name: GetKeyByEnglishName :one
SELECT key
FROM aecheck.translations
WHERE en = $1
LIMIT 1
`

func (q *Queries) GetKeyByEnglishName(ctx context.Context, en string) (string, error) {
	row := q.db.QueryRow(ctx, getKeyByEnglishName, en)
	var key string
	err := row.Scan(&key)
	return key, err
}

const getTranslation = `-- name: GetTranslation :one
SELECT ko, en, ja
FROM aecheck.translations
WHERE key = $1
`

type GetTranslationRow struct {
	Ko string `json:"ko"`
	En string `json:"en"`
	Ja string `json:"ja"`
}

func (q *Queries) GetTranslation(ctx context.Context, key string) (GetTranslationRow, error) {
	row := q.db.QueryRow(ctx, getTranslation, key)
	var i GetTranslationRow
	err := row.Scan(&i.Ko, &i.En, &i.Ja)
	return i, err
}

const insertTranslation = `-- name: InsertTranslation :exec
INSERT INTO aecheck.translations (key, ko, en, ja, created_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
`

type InsertTranslationParams struct {
	Key string `json:"key"`
	Ko  string `json:"ko"`
	En  string `json:"en"`
	Ja  string `json:"ja"`
}

func (q *Queries) InsertTranslation(ctx context.Context, arg InsertTranslationParams) error {
	_, err := q.db.Exec(ctx, insertTranslation,
		arg.Key,
		arg.Ko,
		arg.En,
		arg.Ja,
	)
	return err
}

const updateTranslation = `-- name: UpdateTranslation :exec
UPDATE aecheck.translations
SET
    ko = $2,
    en = $3,
    ja = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE key = $1
`

type UpdateTranslationParams struct {
	Key string `json:"key"`
	Ko  string `json:"ko"`
	En  string `json:"en"`
	Ja  string `json:"ja"`
}

func (q *Queries) UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) error {
	_, err := q.db.Exec(ctx, updateTranslation,
		arg.Key,
		arg.Ko,
		arg.En,
		arg.Ja,
	)
	return err
}
